name = "Green AI Hack"
# license = "MIT"
# licenselink = "https://github.com/panr/hugo-theme-terminal/blob/master/LICENSE.md"
description = "An AI hackathon that explores the trade-off between performance and environmental footprint of AI models."
homepage = "https://greenaihack.org"
# tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "monotone", "multilingual", "personal", "responsive", "simple", "technical", "retro"]
# features = ["blog", "shortcode", "syntax highlighting"]
min_version = 0.90

[author]
  name = "panr"
  homepage = "https://radoslawkoziel.pl"
  twitter = "https://twitter.com/panr"
